spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none


app:
  datasource:
    quiz:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5433/postgres
      username: postgres
      password: postgres

server:
  port: 8090